### ISSUE TITLE
LocalTime.MIDNIGHT causes linker error

### ISSUE THREAD

**Issue by mlvn23** [zoepepper/scalajs-jsjoda#1]
I'm getting a linker error when I use LocalTime.MIDNIGHT in ScalaJs:

[cosmere] $ test:fastOptJS
[info] Compiling 1 Scala source to D:\extradash\src\pathfinder2\nexus\js\target\scala-2.11\classes...
[info] Fast optimizing D:\extradash\src\pathfinder2\midgar\modules\cosmere\chart-client\target\scala-2.11\cosmere-chart-client-test-fastopt.js
[error] Referring to non-existent method java.time.LocalTime$.MIDNIGHT()java.time.LocalTime
[error]   called from com.extrategic.pathfinder.TradingSession$.<init>()

Do you know why?

**Comment by rpiaggio** [comment]
Fixed in 1.0.5. Should be in released in central shortly. Thank you for reporting!
