### ISSUE TITLE
Equals does not seem to work correctly on several classes

### ISSUE THREAD

**Issue by migo** [zoepepper/scalajs-jsjoda#2]
At least for java.time.LocalDate and java.time.Month, the equals function does not seem to work properly.
Looking at the code of LocalDate, equals is implemented by calling com.zoepepper.facades.jsjoda.LocalDate.equals. That, in turn, is not implemented at all, thus probably falling back to reference identity. The function isEqual, however, is implemented. Perhaps that one should be used instead?

**Comment by rpiaggio** [comment]
Hi @migo ! Sorry for the delay.

I see that in the latest version of `js-joda`, `LocalDate.equals` is implemented: https://github.com/js-joda/js-joda/blob/master/src/LocalDate.js#L1645.

I will update dependencies to use the latest release of `js-joda`: `1.2.0`.

As for `Month`, let me investigate further.

**Comment by rpiaggio** [comment]
@migo thank you for reporting this issue.

It's fixed now on version 1.0.6. Might take a few minutes to become available on Maven central.
