### ISSUE TITLE
Non-existent method Instant.from(temporal: TemporalAccessor)

### ISSUE THREAD

**Issue by ThijsBroersen** [zoepepper/scalajs-jsjoda#5]
Instant.from gives me a compile error: `Referring to non-existent method java.time.Instant$.from(java.time.temporal.TemporalAccessor)java.time.Instant`

Looks like the scalajs-jsjoda facade method is different from the original java method, hence the compile error. 
jsjoda: `java.time.Instant.from(temporal: Temporal)`
orinal java: `java.time.Instant.from(temporal: TemporalAccessor)`

Is this done deliberately? If yes, why?

I can work-around this issue by using LocalDateTIme.from(...).toInstant(ZoneOffset.UTC) or by ZonedDateTime.

**Comment by rpiaggio** [comment]
@ThijsBroersen Sorry for the extended delay and thank you very much for reporting this.

It seems like it was a bug. Should be fixed in 1.1.2 which I just released (might take a few hours before it shows up in Maven Central).
