### ISSUE TITLE
Link error

### ISSUE THREAD

**Issue by vpavkin** [zoepepper/scalajs-jsjoda#6]
Hello!

Your project looks as a really promising tool for cross-platform time-based business logic. But I came across following issue.

Here's a simple scalajs program:

```scala
// notice original facade imports

import com.zoepepper.facades.jsjoda.ZonedDateTime
import com.zoepepper.facades.jsjoda.temporal.ChronoUnit

import scala.scalajs.js.annotation.{JSExport, JSExportTopLevel}

object Main {
  @JSExportTopLevel("joda.Main")
  protected def getInstance(): this.type = this

  @JSExport
  def main(): Unit = {
    val t1 = ZonedDateTime.now()
    val t2 = ZonedDateTime.now().plusDays(1L)
    println(t1.until(t2, ChronoUnit.MINUTES))
  }
}
```

It works fine. But when I change imports to `java.time._` to use the drop-in, I get link error:

```scala
// notice changed imports
import java.time.ZonedDateTime
import java.time.temporal.ChronoUnit

// ... previous code unchanged
```
```
 Referring to non-existent method java.time.temporal.Temporal.until(java.time.temporal.Temporal,java.time.temporal.TemporalUnit)scala.Long
```

This makes it very hard to use in cross-platform context. Do you have any ideas for how this can be fixed/worked around?

**Comment by rpiaggio** [comment]
Hi @vpavkin !

Thank you for reporting this issue.

It seems that you may be missing the import:

```
libraryDependencies += "com.zoepepper" %%% "scalajs-jsjoda-as-java-time" % "1.1.1"
```

The project consists of 2 artifacts:
* `scalajs-jsjoda` - A facade for `jsjoda`.
* `scalajs-jsjoda-as-java-time` - A wrapper implementing `java.time._` classes by wrapping `jsjoda` ones.

If you want to use the drop-in replacement for `java.time._` within ScalaJS, you have to import both.

**Comment by vpavkin** [comment]
@rpiaggio Hi :)
I have them both specified in my `build.sbt`:

```
    "com.zoepepper" %%% "scalajs-jsjoda" % "1.1.1",
    "com.zoepepper" %%% "scalajs-jsjoda-as-java-time" % "1.1.1"
```

Some other methods on ZonedDateTime do work, for example `toEpochSecond` works fine. The problem is with `until`.

**Comment by vpavkin** [comment]
I can create a reproducer repo if you like :)

**Comment by rpiaggio** [comment]
Hi @vpavkin! Upon closer look the issue seems to be with the `until` method.

I'm sorry to let you know that I won't be able to look into this until after Jan 15th. In the meantime, please feel free to look into the code and submit a PR.

**Comment by vpavkin** [comment]
@rpiaggio sure, no problem! Will try to approach this one.
Happy holidays! :)

**Comment by vpavkin** [comment]
@rpiaggio I found the issue. It turns out that when I was playing around with scalajs-joda, I also had a dependency on a library, which transitively brought in https://github.com/scala-js/scala-js-java-time.
Linker was not able to chose between that one and `scalajs-jsjoda` drop-in.

I'll send a PR to docs, so that people know about this caveat.

Also, do you mind if I send another PR to bump Scala.js to 0.6.21? There's a really big project at work I want to try your library out on, having a fresh build would be great.

**Comment by rpiaggio** [comment]
@vpavkin Thank you and sorry for the delay. Just merged the PR. I'll update dependency versions and release a new package.
